# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"names": "10_pref.ipynb",
         "short_names": "10_pref.ipynb",
         "df": "10_pref.ipynb",
         "__code2name": "10_pref.ipynb",
         "__name2code": "10_pref.ipynb",
         "name2code": "10_pref.ipynb",
         "code2name": "10_pref.ipynb"}

modules = ["prefecture.py"]

doc_url = "https://vochicong.github.io/jp_pref/"

git_url = "https://github.com/vochicong/jp_pref/tree/master/"

def custom_doc_links(name):
    return None
